export const map = { "compressionlevel":-1,
    "height":40,
    "infinite":false,
    "layers":[
        {
            "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 110, 0, 110, 0, 74, 0, 74, 0, 74, 0, 110, 0, 110, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 146, 0, 147, 0, 74, 0, 74, 0, 74, 0, 147, 0, 148, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 146, 0, 147, 0, 74, 0, 74, 0, 74, 0, 147, 0, 148, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 146, 0, 147, 0, 74, 0, 74, 0, 74, 0, 147, 0, 148, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 146, 0, 147, 0, 74, 0, 74, 0, 74, 0, 147, 0, 148, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            "height":40,
            "id":3,
            "name":"floor",
            "opacity":1,
            "type":"tilelayer",
            "visible":true,
            "width":40,
            "x":0,
            "y":0
        },
        {
            "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 306, 0, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 335, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 376, 0, 343, 0],
            "height":40,
            "id":2,
            "name":"walls",
            "opacity":1,
            "type":"tilelayer",
            "visible":true,
            "width":40,
            "x":0,
            "y":0
        }],
    "nextlayerid":4,
    "nextobjectid":1,
    "orientation":"orthogonal",
    "renderorder":"right-down",
    "tiledversion":"1.7.2",
    "tileheight":16,
    "tilesets":[
        {
            "columns":37,
            "firstgid":1,
            "image":"/public/tiles/tileset x1.png",
            "imageheight":736,
            "imagewidth":1184,
            "margin":0,
            "name":"tileset x1",
            "spacing":0,
            "tilecount":851,
            "tileheight":32,
            "tiles":[
                {
                    "id":0,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":1,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":2,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":3,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":4,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":5,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":6,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":7,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":8,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":9,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":10,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":11,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":12,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":13,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":14,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":37,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":38,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":39,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":40,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":41,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":42,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":43,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":44,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":45,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":46,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":47,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":48,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":49,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":50,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":51,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":72,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":74,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":75,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":76,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":77,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":78,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":79,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":80,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":81,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":82,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":83,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":84,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":85,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":86,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":87,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":88,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":108,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":109,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":110,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":111,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":112,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":113,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":114,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":115,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":116,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":117,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":118,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":119,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":120,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":121,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":122,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":123,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":124,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":125,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":145,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":146,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":147,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":148,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":149,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":150,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":151,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":152,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":153,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":154,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":155,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":156,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":157,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":158,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":159,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":160,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":161,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":162,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":183,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":185,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":186,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":187,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":188,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":189,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":190,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":191,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":192,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":193,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":194,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":195,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":196,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":197,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":198,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":199,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":222,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":223,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":224,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":225,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":226,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":227,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":228,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":229,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":230,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":231,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":232,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":233,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":234,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":235,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":236,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":259,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":260,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":261,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":262,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":263,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":264,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":265,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":266,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":267,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":268,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":269,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":270,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":271,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":272,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":273,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":296,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":297,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":298,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":299,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":300,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":301,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":302,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":303,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":304,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":305,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":306,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":307,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":308,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":309,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":310,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":333,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":334,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":335,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":336,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":337,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":338,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":339,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":340,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":341,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":342,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":343,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":344,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":345,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":346,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":347,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":370,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":371,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":372,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":373,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":374,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":375,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":376,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":377,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":378,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":379,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":380,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":381,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":382,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":383,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                },
                {
                    "id":384,
                    "properties":[
                        {
                            "name":"collides",
                            "type":"bool",
                            "value":true
                        }]
                }],
            "tilewidth":32
        }],
    "tilewidth":16,
    "type":"map",
    "version":"1.6",
    "width":40
};

export default map